### ISSUE TITLE
Alternative implementation

### ISSUE THREAD

**Issue by zflat** [jkitchin/devcontainer#1]
Are you familiar with the tool https://github.com/devcontainers/cli? Here is a discussion on how to accomplish what this package is doing with a little bit of bash and some installed tools like `jq`: https://github.com/devcontainers/cli/issues/59#issuecomment-1209821491. Just pointing this out because you may be able to get more features more easily by creating some bash aliases than maintaining your own implementation of a CLI.

**Comment by jkitchin** [comment]
it figures there would be something like this. Thanks for point it out.
